runtime: nodejs18
service: frontend
handlers:
  - url: /.*
    script: auto
  - url: .*
    script: auto

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 10
  timeout_sec: 8
  failure_threshold: 3
  success_threshold: 1
  app_start_timeout_sec: 1800

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5